In [29]:
import pandas as pd
import requests
import pandas as pd

In [30]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=ad5f333b4cccb1d8cbe21de5d526208a&language=en-US&page=1')

In [31]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [32]:
new_df = pd.DataFrame()

In [35]:
for x in range(1,397):
  response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=ad5f333b4cccb1d8cbe21de5d526208a&language=en-US&page={}'.format(x))
  df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
  new_df = pd.concat([new_df,df],ignore_index=True)

In [37]:
new_df.sample(50)

,id,title,overview,release_date,popularity,vote_average,vote_count
1990,134,"O Brother, Where Art Thou?","In the deep south during the 1930s, three esca...",2000-08-30,4.3279,7.320,4303
2232,509,Notting Hill,London bookstore owner William Thacker's quiet...,1999-05-21,8.2304,7.264,6345
17895,345922,Fist Fight,"When one school teacher gets the other fired, ...",2017-02-16,1.8604,6.100,1258
16984,10307,Stigmata,A young woman with no strong religious beliefs...,1999-09-02,2.4567,6.275,1140
8318,382517,Open Season: Scared Silly,The humans and animals believe a werewolf is o...,2015-12-18,2.4443,6.000,358
17752,12122,Village of the Damned,An American village is visited by some unknown...,1995-04-28,1.4028,6.100,857
14550,105077,Battlestar Galactica: The Plan,When the initial Cylon attack against the Twel...,2009-10-27,1.5402,6.763,445
16552,60420,Like Crazy,A British college student falls for an America...,2011-10-28,1.4241,6.363,1050
16028,199575,These Final Hours,What would you do on the last day on Earth? W...,2014-07-31,3.9072,6.470,574
4019,13285,Barbie Fairytopia: Mermaidia,"In this animated follow-up to Fairytopia, Elin...",2006-03-14,2.9331,6.900,713
14801,9819,Marvin's Room,A leukemia patient attempts to end a 20-year f...,1996-12-18,1.7770,6.710,606
17837,1956,Gerry,Two friends named Gerry become lost in the des...,2002-09-20,0.7894,6.079,321
11370,586940,I Lost My Body,"A story of Naoufel, a young man who is in love...",2019-11-06,1.7389,7.486,1280
5324,626412,Alienoid: Return to the Future,Ean has a critical mission to return to the fu...,2024-01-10,4.4636,6.611,805
3074,26736,Wizards of Waverly Place: The Movie,A young wizard accidentally conjures a spell t...,2009-08-28,2.1147,7.100,1612
16676,11680,The Miser,Based on Moli√®re's play. The children of Harpa...,1980-03-05,1.0358,6.339,446
10256,538362,On My Skin,The incredible true story behind the most cont...,2018-09-12,1.1126,8.032,1861
3943,307103,SK1,"The hunt, capture and trial of Guy Georges, on...",2015-01-07,0.5885,6.886,319
110,1160164,TAYLOR SWIFT | THE ERAS TOUR,A concert film documenting Taylor Swift's reco...,2023-10-13,2.8353,8.214,450
16396,411741,Ingrid Goes West,Ingrid becomes obsessed with a social network ...,2017-08-11,3.2988,6.397,997
5299,21407,The Collector,"Desperate to repay his debt to his ex-wife, an...",2009-07-09,3.3085,6.616,1536
7058,446101,Assassination Nation,After an anonymous hacker begins leaking the p...,2018-09-21,1.8047,6.255,850
11338,12169,The First Day of the Rest of Your Life,A sprawling drama centered on five key days in...,2008-07-23,1.1759,7.494,486
3914,232672,Blended,Recently divorced mom Lauren and widowed dad J...,2014-05-21,9.6366,6.892,3635
3628,491472,At Eternity's Gate,Famed but tormented artist Vincent van Gogh sp...,2018-11-15,1.4527,7.000,1486
309,595,To Kill a Mockingbird,"Scout Finch, 6, and her older brother Jem live...",1962-12-20,4.2573,7.990,2701
14929,421447,The Climb,"A true story of Samy, native of La Courneuve, ...",2017-01-25,0.8148,6.700,869
7862,12220,The Story of Us,Ben and Katie Jordan are a married couple who ...,1999-10-14,1.2034,6.071,329
8450,151960,Planes,Dusty is a cropdusting plane who dreams of com...,2013-08-09,4.1313,5.919,1738
16560,315880,Correspondence,"The relationship between Ed, a married astrono...",2016-01-14,0.8498,6.361,403
9397,890541,7 Women and a Murder,"When the family patriarch is murdered, seven w...",2021-12-25,0.8774,5.500,368
13440,300,The Science of Sleep,A man entranced by his dreams and imagination ...,2006-06-25,0.9942,6.996,786
690,17483,Shelter,"Forced to give up his dreams of art school, Za...",2007-06-16,1.2132,7.800,483
12788,254172,Fathers and Daughters,A Pulitzer-winning writer grapples with being ...,2015-10-01,1.8611,7.136,987
13606,13198,Wristcutters: A Love Story,"Zia, distraught over breaking up with his girl...",2007-10-19,1.6775,6.958,572
9117,10154,Mickey Blue Eyes,An English auctioneer proposes to the daughter...,1999-08-16,1.0672,5.686,567
3249,19186,The Parent Trap,"Two identical twin sisters, separated at birth...",1961-05-13,3.3042,7.037,394
9311,575479,An Easy Girl,"Na√Øma has just turned 16. This summer, she wil...",2019-08-28,2.1569,5.600,355
3974,541134,The Good Nurse,Suspicious that her colleague is responsible f...,2022-10-19,3.1685,6.878,1311
10128,851644,20th Century Girl,"In 1999, a teen girl keeps close tabs on a boy...",2022-10-06,13.1583,8.200,740
13727,429199,The Other Side of Hope,A restaurateur befriends a Syrian refugee who ...,2017-02-03,1.1127,6.932,329
4712,459992,Long Shot,Journalist Fred Flarsky reunites with his chil...,2019-05-02,2.3041,6.700,2749
1938,289222,The Zookeeper's Wife,"The account of keepers of the Warsaw Zoo, Jan ...",2017-03-24,2.1964,7.331,1521
747,843906,Straight Outta Nowhere: Scooby-Doo! Meets Cour...,"With Mystery, Inc. on the tail of a strange ob...",2021-09-14,1.8141,7.700,390
778,451945,BPM (Beats per Minute),"Paris, in the early 1990s: a group of young ac...",2017-08-23,1.0261,7.700,1352
7494,9103,The Quest,"Ghang-gheng, the ancient winner-take-all compe...",1996-04-19,2.5741,6.156,745
11457,18197,Running on Empty,The Popes are a family who haven't been able t...,1988-09-09,1.3691,7.500,322
1008,15137,Evangelion: 1.0 You Are (Not) Alone,"After the Second Impact, Tokyo-3 is being atta...",2007-09-01,3.8539,7.607,1006
3003,321741,Concussion,A dramatic thriller based on the incredible tr...,2015-11-12,2.5169,7.086,2604
11914,33701,French Fried Vacation 2,In this sequel to Les Bronzes (1978) summer ha...,1979-11-22,1.5817,7.338,1224

In [38]:
new_df.to_csv('movie_database')

In [39]:
df1 = pd.read_csv('/content/movie_database')

In [40]:
df1

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,27.0754,8.712,28521
1,1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,27.6819,8.688,21597
2,2,803796,KPop Demon Hunters,"When K-pop superstars Rumi, Mira and Zoey aren...",2025-06-20,220.7591,8.612,493
3,3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,14.4935,8.571,13045
4,4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,12.8592,8.565,16521
...,...,...,...,...,...,...,...,...
17915,17915,56339,Whatsoeverly,Corrupt and sleazy entrepreneur Cetto La Qualu...,2011-01-21,0.4917,6.056,532
17916,17916,25769,Carriers,A deadly virus has spread across the globe. Co...,2009-09-04,3.0030,6.056,1423
17917,17917,10396,Tequila Sunrise,"In a seaside California town, best friends Mac...",1988-12-02,1.6754,6.100,531
17918,17918,9416,Money Talks,"Sought by police and criminals, a small-time h...",1997-08-22,2.8480,6.056,396
17919,17919,9208,Broken Arrow,When rogue stealth-fighter pilot Vic Deakins d...,1996-02-09,3.4535,6.056,1572

In [41]:
df1.head(3)

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,27.0754,8.712,28521
1,1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,27.6819,8.688,21597
2,2,803796,KPop Demon Hunters,"When K-pop superstars Rumi, Mira and Zoey aren...",2025-06-20,220.7591,8.612,493