In [ ]:
import pandas as pd
import numpy as np

In [ ]:
date = pd.read_csv('/content/orders.csv')
time = pd.read_csv('/content/messages.csv')

In [283]:
date

           date  product_id  city_id  orders
0    2019-12-10        5628       25       3
1    2018-08-15        3646       14     157
2    2018-10-23        1859       25       1
3    2019-08-17        7292       25       1
4    2019-01-06        4344       25       3
..          ...         ...      ...     ...
995  2018-10-08         255       13       1
996  2018-12-06        5521        7       1
997  2019-05-07         487       26      14
998  2019-03-03        1503       21       2
999  2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [284]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [285]:
date['date'] = pd.to_datetime(date['date'])

In [286]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [287]:
date

          date  product_id  city_id  orders
0   2019-12-10        5628       25       3
1   2018-08-15        3646       14     157
2   2018-10-23        1859       25       1
3   2019-08-17        7292       25       1
4   2019-01-06        4344       25       3
..         ...         ...      ...     ...
995 2018-10-08         255       13       1
996 2018-12-06        5521        7       1
997 2019-05-07         487       26      14
998 2019-03-03        1503       21       2
999 2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [288]:
date['date_year'] = date['date'].dt.year

In [289]:
date

          date  product_id  city_id  orders  date_year
0   2019-12-10        5628       25       3       2019
1   2018-08-15        3646       14     157       2018
2   2018-10-23        1859       25       1       2018
3   2019-08-17        7292       25       1       2019
4   2019-01-06        4344       25       3       2019
..         ...         ...      ...     ...        ...
995 2018-10-08         255       13       1       2018
996 2018-12-06        5521        7       1       2018
997 2019-05-07         487       26      14       2019
998 2019-03-03        1503       21       2       2019
999 2019-10-15        6371        7      22       2019

[1000 rows x 5 columns]

In [290]:
date['date_month'] = date['date'].dt.month

In [291]:
date

          date  product_id  city_id  orders  date_year  date_month
0   2019-12-10        5628       25       3       2019          12
1   2018-08-15        3646       14     157       2018           8
2   2018-10-23        1859       25       1       2018          10
3   2019-08-17        7292       25       1       2019           8
4   2019-01-06        4344       25       3       2019           1
..         ...         ...      ...     ...        ...         ...
995 2018-10-08         255       13       1       2018          10
996 2018-12-06        5521        7       1       2018          12
997 2019-05-07         487       26      14       2019           5
998 2019-03-03        1503       21       2       2019           3
999 2019-10-15        6371        7      22       2019          10

[1000 rows x 6 columns]

In [292]:
date['date_day'] = date['date'].dt.day

In [293]:
date

          date  product_id  city_id  orders  date_year  date_month  date_day
0   2019-12-10        5628       25       3       2019          12        10
1   2018-08-15        3646       14     157       2018           8        15
2   2018-10-23        1859       25       1       2018          10        23
3   2019-08-17        7292       25       1       2019           8        17
4   2019-01-06        4344       25       3       2019           1         6
..         ...         ...      ...     ...        ...         ...       ...
995 2018-10-08         255       13       1       2018          10         8
996 2018-12-06        5521        7       1       2018          12         6
997 2019-05-07         487       26      14       2019           5         7
998 2019-03-03        1503       21       2       2019           3         3
999 2019-10-15        6371        7      22       2019          10        15

[1000 rows x 7 columns]

In [294]:
date['date_month_name'] = date['date'].dt.month_name()

In [295]:
date

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name
0,2019-12-10,5628,25,3,2019,12,10,December
1,2018-08-15,3646,14,157,2018,8,15,August
2,2018-10-23,1859,25,1,2018,10,23,October
3,2019-08-17,7292,25,1,2019,8,17,August
4,2019-01-06,4344,25,3,2019,1,6,January
...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,8,October
996,2018-12-06,5521,7,1,2018,12,6,December
997,2019-05-07,487,26,14,2019,5,7,May
998,2019-03-03,1503,21,2,2019,3,3,March
999,2019-10-15,6371,7,22,2019,10,15,October

In [296]:
date['date_week'] = date['date'].dt.dayofweek

In [297]:
date

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_week
0,2019-12-10,5628,25,3,2019,12,10,December,1
1,2018-08-15,3646,14,157,2018,8,15,August,2
2,2018-10-23,1859,25,1,2018,10,23,October,1
3,2019-08-17,7292,25,1,2019,8,17,August,5
4,2019-01-06,4344,25,3,2019,1,6,January,6
...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,8,October,0
996,2018-12-06,5521,7,1,2018,12,6,December,3
997,2019-05-07,487,26,14,2019,5,7,May,1
998,2019-03-03,1503,21,2,2019,3,3,March,6
999,2019-10-15,6371,7,22,2019,10,15,October,1

In [298]:
date['date_day_name'] = date['date'].dt.day_name()

In [299]:
date

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_week,date_day_name
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,17,August,5,Saturday
4,2019-01-06,4344,25,3,2019,1,6,January,6,Sunday
...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,8,October,0,Monday
996,2018-12-06,5521,7,1,2018,12,6,December,3,Thursday
997,2019-05-07,487,26,14,2019,5,7,May,1,Tuesday
998,2019-03-03,1503,21,2,2019,3,3,March,6,Sunday
999,2019-10-15,6371,7,22,2019,10,15,October,1,Tuesday

In [300]:
date['date_weekend'] = np.where(date['date_day_name'].isin(['Saturday','Sunday']),1,0)
date.drop(columns=['product_id','city_id','orders'])

,date,date_year,date_month,date_day,date_month_name,date_week,date_day_name,date_weekend
0,2019-12-10,2019,12,10,December,1,Tuesday,0
1,2018-08-15,2018,8,15,August,2,Wednesday,0
2,2018-10-23,2018,10,23,October,1,Tuesday,0
3,2019-08-17,2019,8,17,August,5,Saturday,1
4,2019-01-06,2019,1,6,January,6,Sunday,1
...,...,...,...,...,...,...,...,...
995,2018-10-08,2018,10,8,October,0,Monday,0
996,2018-12-06,2018,12,6,December,3,Thursday,0
997,2019-05-07,2019,5,7,May,1,Tuesday,0
998,2019-03-03,2019,3,3,March,6,Sunday,1
999,2019-10-15,2019,10,15,October,1,Tuesday,0

In [301]:
date

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_week,date_day_name,date_weekend
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,17,August,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,6,January,6,Sunday,1
...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,8,October,0,Monday,0
996,2018-12-06,5521,7,1,2018,12,6,December,3,Thursday,0
997,2019-05-07,487,26,14,2019,5,7,May,1,Tuesday,0
998,2019-03-03,1503,21,2,2019,3,3,March,6,Sunday,1
999,2019-10-15,6371,7,22,2019,10,15,October,1,Tuesday,0

In [302]:
date['date_quarter'] = date['date'].dt.quarter

In [303]:
date

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_week,date_day_name,date_weekend,date_quarter
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday,0,4
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday,0,3
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday,0,4
3,2019-08-17,7292,25,1,2019,8,17,August,5,Saturday,1,3
4,2019-01-06,4344,25,3,2019,1,6,January,6,Sunday,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,8,October,0,Monday,0,4
996,2018-12-06,5521,7,1,2018,12,6,December,3,Thursday,0,4
997,2019-05-07,487,26,14,2019,5,7,May,1,Tuesday,0,2
998,2019-03-03,1503,21,2,2019,3,3,March,6,Sunday,1,1
999,2019-10-15,6371,7,22,2019,10,15,October,1,Tuesday,0,4

In [304]:
date['date_semester'] = np.where(date['date_quarter'].isin([1,2]),1,2)

In [305]:
date

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_week,date_day_name,date_weekend,date_quarter,date_semester
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday,0,4,2
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday,0,3,2
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday,0,4,2
3,2019-08-17,7292,25,1,2019,8,17,August,5,Saturday,1,3,2
4,2019-01-06,4344,25,3,2019,1,6,January,6,Sunday,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,8,October,0,Monday,0,4,2
996,2018-12-06,5521,7,1,2018,12,6,December,3,Thursday,0,4,2
997,2019-05-07,487,26,14,2019,5,7,May,1,Tuesday,0,2,1
998,2019-03-03,1503,21,2,2019,3,3,March,6,Sunday,1,1,1
999,2019-10-15,6371,7,22,2019,10,15,October,1,Tuesday,0,4,2

In [306]:
import datetime

In [307]:
Today = datetime.datetime.today()

In [308]:
Today

datetime.datetime(2025, 7, 19, 15, 14, 12, 220652)

In [310]:
date

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_week,date_day_name,date_weekend,date_quarter,date_semester
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday,0,4,2
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday,0,3,2
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday,0,4,2
3,2019-08-17,7292,25,1,2019,8,17,August,5,Saturday,1,3,2
4,2019-01-06,4344,25,3,2019,1,6,January,6,Sunday,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,8,October,0,Monday,0,4,2
996,2018-12-06,5521,7,1,2018,12,6,December,3,Thursday,0,4,2
997,2019-05-07,487,26,14,2019,5,7,May,1,Tuesday,0,2,1
998,2019-03-03,1503,21,2,2019,3,3,March,6,Sunday,1,1,1
999,2019-10-15,6371,7,22,2019,10,15,October,1,Tuesday,0,4,2

In [311]:
(Today - date['date']).dt.days

0      2048
1      2530
2      2461
3      2163
4      2386
       ...
995    2476
996    2417
997    2265
998    2330
999    2104
Name: date, Length: 1000, dtype: int64

In [312]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [313]:
time.info(

)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [314]:
time['date'] = pd.to_datetime(time['date'])

In [315]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [316]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [317]:
time

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0
...,...,...,...,...,...
995,2012-03-16 00:50:00,ПАРЕНЬ СДЕЛАЕТ МАССАЖ ЖЕНЩИНАМ -066-877-32-44,0,50,0
996,2014-01-23 23:14:00,сельский п 23 ищу девушку для отношений,23,14,0
997,2012-10-15 23:37:00,Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...,23,37,0
998,2012-06-21 23:34:00,7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14,23,34,0
999,2014-06-19 23:25:00,Парень поласкает девушке... т.0662035584,23,25,0

In [318]:
time['time'] = time['date'].dt.time

In [321]:
Today - time['date']

0     4234 days 14:24:12.220652
1     4098 days 15:34:12.220652
2     4584 days 14:53:12.220652
3     3886 days 14:43:12.220652
4     4283 days 16:03:12.220652
                 ...
995   4873 days 14:24:12.220652
996   4194 days 16:00:12.220652
997   4659 days 15:37:12.220652
998   4775 days 15:40:12.220652
999   4047 days 15:49:12.220652
Name: date, Length: 1000, dtype: timedelta64[ns]

In [323]:
(Today - time['date']) / np.timedelta64(1,'h')

0      101630.403395
1       98367.570061
2      110030.886728
3       93278.720061
4      102808.053395
           ...
995    116966.403395
996    100672.003395
997    111831.620061
998    114615.670061
999     97143.820061
Name: date, Length: 1000, dtype: float64

In [324]:
(Today - time['date']) / np.timedelta64(1,'m')

0      6.097824e+06
1      5.902054e+06
2      6.601853e+06
3      5.596723e+06
4      6.168483e+06
           ...
995    7.017984e+06
996    6.040320e+06
997    6.709897e+06
998    6.876940e+06
999    5.828629e+06
Name: date, Length: 1000, dtype: float64

In [325]:
(Today - time['date']) / np.timedelta64(1,'s')

0      3.658695e+08
1      3.541233e+08
2      3.961112e+08
3      3.358034e+08
4      3.701090e+08
           ...
995    4.210791e+08
996    3.624192e+08
997    4.025938e+08
998    4.126164e+08
999    3.497178e+08
Name: date, Length: 1000, dtype: float64