In [789]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [790]:
df = pd.read_csv('/content/cars.csv')

In [791]:
df.shape

(8128, 5)

In [792]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [793]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [794]:
x = df.drop('selling_price',axis=1)
y = df['selling_price']

In [795]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [796]:
x_train.shape,x_test.shape

((6502, 4), (1626, 4))

In [797]:
x_train

         brand  km_driven    fuel                 owner
6518      Tata       2560  Petrol           First Owner
6144     Honda      80000  Petrol          Second Owner
6381   Hyundai     150000  Diesel  Fourth & Above Owner
438     Maruti     120000  Diesel          Second Owner
5939    Maruti      25000  Petrol           First Owner
...        ...        ...     ...                   ...
5226  Mahindra     120000  Diesel           First Owner
5390    Maruti      80000  Diesel          Second Owner
860    Hyundai      35000  Petrol           First Owner
7603    Maruti      27000  Diesel           First Owner
7270    Maruti      70000  Petrol          Second Owner

[6502 rows x 4 columns]

In [841]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=np.int32,drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

In [798]:
x_train['owner'].value_counts()

owner
First Owner             4240
Second Owner            1684
Third Owner              433
Fourth & Above Owner     141
Test Drive Car             4
Name: count, dtype: int64

In [799]:
from sklearn.preprocessing import OneHotEncoder

In [800]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [801]:
x_train_ohe = ohe.fit_transform(x_train[['fuel','owner']])
x_test_ohe = ohe.transform(x_test[['fuel','owner']])

In [802]:
x_train_ohe.shape

(6502, 7)

In [803]:
np.hstack((x_train[['brand','km_driven']].values,x_train_ohe))

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], dtype=object)

In [819]:
counts = df['brand'].value_counts()

threshold = 100

In [834]:
repl = counts[counts <= threshold].values

In [835]:
repl

array([81, 71, 67, 65, 54, 47, 40, 34, 31, 14,  6,  6,  5,  4,  4,  3,  3,
        1,  1,  1])

In [838]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'),dtype=np.int32).sample(5)

,Ambassador,Ashok,Audi,BMW,Chevrolet,Daewoo,Datsun,Fiat,Force,Ford,...,Mitsubishi,Nissan,Opel,Peugeot,Renault,Skoda,Tata,Toyota,Volkswagen,Volvo
6861,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7099,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2221,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2869,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0